name: stronzflix
description: "Streaming application."
publish_to: 'none'

version: 0.2.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  async: ^2.11.0
  audio_service: ^0.18.13
  audio_service_mpris: ^0.1.5
  cast: 
    git:
      url: https://github.com/guyluz11/flutter_cast.git
      ref: updating_bonsoir_pacakge
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.7
  flutter_hls_parser: ^2.0.1
  flutter_svg: ^2.0.10+1
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^1.2.1
  # media_kit: ^1.1.10+1
  image: ^4.2.0
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./media_kit
      ref: main
  # media_kit_libs_video: ^1.0.4
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./libs/universal/media_kit_libs_video
      ref: main
  # media_kit_video: ^1.2.4
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./media_kit_video
      ref: main
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  peerdart: ^0.5.4
  pointycastle: ^3.9.1
  process_run: ^0.14.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  # smtc_windows: ^0.1.3
  smtc_windows:
    git:
      url: https://github.com/Bonfra04/smtc_windows.git
      path: ./packages/smtc_windows
      ref: main
  typed_data: ^1.3.2
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./media_kit
      ref: main
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
