name: Build MacOS
on:
  push:
    branches:
      - "single-app"

jobs:
  Run-build:
    name: Run build MacOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build macos --release --no-codesign
